### ISSUE TITLE
Error loading preference bundle for iHide

### ISSUE THREAD

**Issue by olixerr** [Kc57/iHide#3]
**Describe the bug**

**To Reproduce**
1. Installed through Zebra package manager
2. Opened settings 
3. Navigated to iHide preference pane
4. See Error ‘There was an error loading the preference bundle for iHide.

**Expected behavior**
The iHide preferences to appear, duh :P

**Screenshots**
![DA5C7ADB-717A-4D6C-9FC6-9362E6458EA0](https://user-images.githubusercontent.com/48519166/132013888-cbd9373b-0843-42e7-88e0-879d5f9f3fe7.png)

**Device Information (please complete the following information):**
 - Device: iPhone 12 Pro
 - OS: iOS 14.3
 - Jailbreak Method: Taurine 1.1.0
 - iHide Version: 1.0.2 

**Additional context**

**Comment by Kc57** [comment]
Fixed in afaf2f62e795051dfa789936dae87a2f1f051e84 by updating the ARCHS in the preference bundle makefile
