### ISSUE TITLE
Build error: 'Foundation/Foundation.h' file not found

### ISSUE THREAD

**Issue by jayluxferro** [Kc57/iHide#9]
**Build error**
`fatal error: 'Foundation/Foundation.h' file not found`

**To Reproduce**
`make package`

**Screenshots**
![Screenshot 2021-09-11 at 03 38 27](https://user-images.githubusercontent.com/8394019/132935025-4fff75fe-c304-4d69-a258-83991658620e.png)

**Device Information:**
 - Xcode 12.5.1 
 - theos 2.5
 - theos-sdk iOS14.4

**Comment by Kc57** [comment]
Thanks for your interest in the project!

The error you are receiving is not a bug in iHide but an issue with your environment. Make sure you follow the Theos setup carefully and have the proper SDKs installed. You can try using the ones I listed below:

- Theos Setup: https://github.com/theos/theos/wiki/Installation-macOS
- SDKs: https://github.com/xybp888/iOS-SDKs

Try inspecting your SDK folder for the following:

`iPhoneOSXX.Y.sdk/System/Library/Frameworks/Foundation.framework`

Where *XX.Y* is the version of iOS SDK you are building against. You can also update the makefile to point to a specific SDK.

**Comment by jayluxferro** [comment]
Thanks. The link to sdk repo helped.
